name: 'Publish MFE static assets'
description: 'Publish MFE static assets'
inputs:
  aws-role-to-assume:
    description: 'AWS IAM role to assume'
    required: true

  aws-region:
    description: 'AWS Resource Region'
    required: true

  submodules-pat:
    description: 'personal access token to be able to checkout git submodules'
    required: true

  app-name:
    description: 'MFE app name (e.g. search-mfe)'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.submodules-pat }}
        submodules: 'true'

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - run: aws sts get-caller-identity
      shell: bash

    - uses: actions/download-artifact@v2
      with:
        name: next-static-assets
        path: build/static-assets/next

    - uses: actions/download-artifact@v2
      with:
        name: public-static-assets
        path: build/static-assets/public

    - name: publish static assets
      env:
        GIT_SHA: ${{ steps.short-sha.outputs.sha }}
      shell: bash
      run: ./mfe-infrastructure/ci/publish-static-assets.sh ${{ inputs.app-name }} ${{ env.GIT_SHA }}
