name: 'Publish MFE static assets'
description: 'Publish MFE static assets'
inputs:
  aws-role-to-assume:
    description: 'AWS IAM role to assume'
    required: true

  aws-region:
    description: 'AWS Resource Region'
    required: true

  submodules-pat:
    description: 'personal access token to be able to checkout git submodules'
    required: true

  app-name:
    description: 'MFE app name (e.g. search-mfe)'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.submodules-pat }}
        submodules: 'true'

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - run: aws sts get-caller-identity
      shell: bash

    - uses: actions/download-artifact@v2
      with:
        name: next-static-assets
        path: build/static-assets/next

    - uses: actions/download-artifact@v2
      with:
        name: public-static-assets
        path: build/static-assets/public

    - name: publish static assets
      env:
        GIT_SHA: ${{ steps.short-sha.outputs.sha }}
      shell: bash
      run: |
        STATIC_ASSETS_BUCKET=$(aws ssm get-parameters --names /checkout/dev/s3/static_assets_mfe/bucket_name --with-decryption --region ${{ inputs.aws-region }} | jq -r ".Parameters[0].Value")

        CACHE_CONTROL_HEADER="public, max-age=31536000, immutable"

        NEXTJS_STATIC_ASSETS_DIR="build/static-assets/next/static"
        PUBLIC_STATIC_ASSETS_DIR="build/static-assets/public/"

        PUBLIC_STATIC_ASSETS_STAGING_DIR="../stage/"

        mkdir -p $PUBLIC_STATIC_ASSETS_STAGING_DIR

        cp -r $PUBLIC_STATIC_ASSETS_DIR $PUBLIC_STATIC_ASSETS_STAGING_DIR

        find $PUBLIC_STATIC_ASSETS_STAGING_DIR -type f -name "mockServiceWorker.js" -delete

        echo "Uploading static assets for revision $GIT_HASH..."
        echo "Checking for existing static assets for this revision..."

        echo "Uploading Nextjs static assets directory to $STATIC_ASSETS_BUCKET/$APP_NAME/$GIT_HASH/_next/static.."
        aws s3 cp $NEXTJS_STATIC_ASSETS_DIR s3://$STATIC_ASSETS_BUCKET/$APP_NAME/$GIT_HASH/_next/static --recursive --cache-control "$CACHE_CONTROL_HEADER"

        echo "Uploading public files directory to $STATIC_ASSETS_BUCKET/$APP_NAME/$GIT_HASH/"
        aws s3 cp $PUBLIC_STATIC_ASSETS_STAGING_DIR s3://$STATIC_ASSETS_BUCKET/$APP_NAME/$GIT_HASH/ --recursive --cache-control "$CACHE_CONTROL_HEADER"

        echo "Static assets upload complete. See previous output for status."
