name: "Publish MFE static assets"
description: "Publish MFE static assets"
inputs:
  aws-access-key-id:
    description: 'AWS Access Key Id'
    required: true

  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true

  aws-region:
    description: 'AWS Resource Region'
    required: true

  submodules-pat-token:
    description: 'Submodule PAT Token'
    required: true

  app-name:
    description: 'MFE app name (e.g. search-mfe)'
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.submodules-pat-token }}
        submodules: 'true'
        
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        
    - uses: actions/download-artifact@v2
      with:
        name: next-static-assets
        path: build/static-assets/next
        
    - uses: actions/download-artifact@v2
      with:
        name: public-static-assets
        path: build/static-assets/public
        
    - name: ls artifacts
      run: ls build/static-assets/next && ls build/static-assets/public
      
    - name: publish static assets
      env:
        GIT_SHA: ${{ steps.short-sha.outputs.sha }}
      run: ./mfe-infrastructure/ci/publish-static-assets.sh ${{ inputs.app-name }} ${{ env.GIT_SHA }}
